name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout journal
        uses: actions/checkout@v2
        with:
          path: journal
      - name: Checkout scaladown
        uses: actions/checkout@v2
        with:
          repository: andrew-selvia/scaladown
          path: scaladown
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          repository: andrew-selvia/website
          path: website
      - name: Transform articles from .md to .html
        run: |-
          rm -rf website/.git
          rm -rf website/journal
          cd scaladown
          /usr/bin/sbt "runMain Main ../journal ../website/journal"
          /usr/bin/sbt "runMain ZioSiteMap ../website/journal ../website"
      - name: Push to website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.JOURNAL_PUBLISHING_PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'website'
          destination-github-username: 'andrew-selvia'
          destination-repository-name: 'website'
          user-email: andrew@selvia.com
          target-branch: main
